import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Nav/NavBar";
import Footer from "./components/Footer/page";

const ptSans = PT_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ptSans.className} antialiased min-h-screen flex flex-col`}
      >
        <NavBar />
        <main className="flex-grow">{children}</main>{" "}
        {/* Pushes footer to the bottom */}
        <Footer />
      </body>
    </html>
  );
}
